### ISSUE TITLE
Fails tests with Python3

### ISSUE THREAD

**Issue by jbaum98** [sdispater/pastel#4]
I'm packaging `pastel` for `nixpkgs` and for Python3, and the tests are failing with

```
running egg_info
writing pastel.egg-info/PKG-INFO
writing dependency_links to pastel.egg-info/dependency_links.txt
writing top-level names to pastel.egg-info/top_level.txt
reading manifest file 'pastel.egg-info/SOURCES.txt'
writing manifest file 'pastel.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 51, in <module>
    setup(**kwargs)
  File "/nix/store/r9asxjad4m81h4dmkhxlmqmk7p7xwbdf-python3.7-bootstrapped-pip-18.1/lib/python3.7/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/nix/store/5di2wpc5h7faqidsikgb94rwdbwy2y3l-python3-3.7.2/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/nix/store/5di2wpc5h7faqidsikgb94rwdbwy2y3l-python3-3.7.2/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/nix/store/5di2wpc5h7faqidsikgb94rwdbwy2y3l-python3-3.7.2/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/nix/store/r9asxjad4m81h4dmkhxlmqmk7p7xwbdf-python3.7-bootstrapped-pip-18.1/lib/python3.7/site-packages/setuptools/command/test.py", line 228, in run
    self.run_tests()
  File "/nix/store/r9asxjad4m81h4dmkhxlmqmk7p7xwbdf-python3.7-bootstrapped-pip-18.1/lib/python3.7/site-packages/setuptools/command/test.py", line 250, in run_tests
    exit=False,
  File "/nix/store/5di2wpc5h7faqidsikgb94rwdbwy2y3l-python3-3.7.2/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/nix/store/5di2wpc5h7faqidsikgb94rwdbwy2y3l-python3-3.7.2/lib/python3.7/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/nix/store/5di2wpc5h7faqidsikgb94rwdbwy2y3l-python3-3.7.2/lib/python3.7/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/nix/store/5di2wpc5h7faqidsikgb94rwdbwy2y3l-python3-3.7.2/lib/python3.7/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/nix/store/5di2wpc5h7faqidsikgb94rwdbwy2y3l-python3-3.7.2/lib/python3.7/unittest/loader.py", line 347, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/nix/store/5di2wpc5h7faqidsikgb94rwdbwy2y3l-python3-3.7.2/lib/python3.7/unittest/loader.py", line 404, in _find_tests
    full_path, pattern, namespace)
  File "/nix/store/5di2wpc5h7faqidsikgb94rwdbwy2y3l-python3-3.7.2/lib/python3.7/unittest/loader.py", line 481, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/nix/store/r9asxjad4m81h4dmkhxlmqmk7p7xwbdf-python3.7-bootstrapped-pip-18.1/lib/python3.7/site-packages/setuptools/command/test.py", line 54, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/nix/store/5di2wpc5h7faqidsikgb94rwdbwy2y3l-python3-3.7.2/lib/python3.7/unittest/loader.py", line 212, in loadTestsFromName
    (obj, test))
TypeError: calling <function pastel at 0x7ffff1adb6a8> returned <pastel.pastel.Pastel object at 0x7ffff1acf860>, not a test
```

**Comment by jbaum98** [comment]
Sorry this was my mistake. The failure had to do with my packaging and wasn't your fault. Sorry for the trouble.
